### ISSUE TITLE
Security vulnerability `/api/kytos/core/config` is exposing `options.jwt_secret`

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#370]
Security vulnerability `/api/kytos/core/config` is exposing `options.jwt_secret`, this endpoint has been around since 2017, and it ended up exposing all options, since jwt_secret is also included in the options it's exposing it, which it shouldn't. 

https://github.com/kytos-ng/kytos/blob/master/kytos/core/controller.py#L409-L410

```
❯ http localhost:8181/api/kytos/core/config | jq .jwt_secret
"2f5846e9652b42ada855766d0d07d6ef"
```

This should be fixed on `2023.1`. 

Network operators who have been using any `@authenticated` endpoint should reconfigure their `jwt_secret` to be extra safe. As far as I know AmLight isn't still using it in production, cc'ing @italovalcy for his information. 

The `jwt_secret` doesn't directly expose user tokens, but it's used for decoding and decoding in the algorithm, that's why it's a secret (for users who want to better understand the impact)

**Comment by italovalcy** [comment]
Thanks a lot for finding this vulnerability and reporting, Vinicius! We are using, but our Kytos instance is behind an HTTP proxy that filters some endpoints allowing just known routes (this particular route is denied, for instance). Anyway, I agree this issue is critical and should be addressed asap.
