### ISSUE TITLE
Possible race condition on interface available tag?

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/kytos#507]
Hi,

This happened in a "fresh" environment, where we executed the migration scripts from an existing database, the interface below belong to a switch which was deactivated, and there was no EVC on that switches.

Why this didnt update when run the migration script? (maybe this interface was not processed?)

```
kytos $> sw.interfaces[27].available_tags
Out[29]: {'vlan': [[1, 35], [38, 53], [55, 538], [543, 4095]]}

kytos $> sw.interfaces[27].tag_ranges
Out[30]: {'vlan': [[1, 4095]]}
```

I checked all the EVCs and didnt find anything referring to this switch/interface.

To workaround this issue, I forced the `sw.interfaces[27].available_tags  = sw.interfaces[27].tag_ranges `

**Comment by viniarck** [comment]
The workaround looks good and glad you managed to apply it @italovalcy. 

This interface port number `27` since it's using tag ranges, it got converted by the script. 

Would you happen to have a DB collection dump of the day prior to this? If you do, it'd be great to confirm which available_vlans it had. Other than that, if the available_vlans indeed were as expected, then it could be a leak where vlans were allocated but never released correctly. 

What we can also do, is to provide a new script that should check against all interfaces from `switches` collection and checking if exists a corresponding `interface_details`, and then also checking if there is any document on `interface_details` and checking if the `available_tags: vlan` is coherent, by checking if the consumed vlans are from existing EVCs and the of_lldp vlan. If vlans are missing then needs to be investigated.

**Comment by Ktmi** [comment]
Which migration script was used for this? Are we talking about the topology 2023.2.0 script?

**Comment by italovalcy** [comment]
yes, David, the migration script for 2023.2.0 (topology)

**Comment by Alopalao** [comment]
@italovalcy The script relays in the old DB `interface_details`, Do you have that collection before the migration? If the `interface_details` has some values used even though the switch was disabled, the script will consider those values and create an `available_vlans`.

**Comment by Alopalao** [comment]
I checked an old `interface_details` collection and found an interface with the same available VLANs. This looks to be the result of inconsistency `interface_details` and misguided migration script. It should not be a problem with new provided scripts to use and make VLANs available.

**Comment by viniarck** [comment]
For those running older version 2023.2, make sure to [use these console scripts that Aldo mentioned](https://github.com/kytos-ng/topology/tree/master/scripts/console/2023.2.0). 

Let's go ahead and close the issue then. Thanks, guys. 

If anything else new shows up let's handle as a new issue for clarity.
